[tool.ruff]
line-length = 100
target-version = "py311"

# Sélection de règles utiles pour data apps :
# - F : erreurs (imports inutiles, variables non utilisées)
# - E/W : style de base
# - B : bugs (flake8-bugbear)
# - S : sécurité (flake8-bandit) -> détecte patterns dangereux
# - I : imports triés
select = ["F", "E", "W", "B", "S", "I"]

# Exemple : ignorer certains faux positifs si besoin
ignore = []

[tool.ruff.lint.per-file-ignores]
# On peut tolérer certains patterns en tests
"tests/**.py" = ["S101"]  # asserts en tests
