name: Mon Premier Workflow

on:
  push:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dire bonjour
      run: echo "Bonjour ! Ma premiÃ¨re GitHub Action fonctionne ðŸŽ‰"
    
    - name: Afficher la date
      run: date
    
    - name: Afficher des infos systÃ¨me
      run: |
        echo "OS: $RUNNER_OS"
        echo "DÃ©pÃ´t: $GITHUB_REPOSITORY"
        echo "Branch: $GITHUB_REF"
